
runtime: python27
api_version: 1
threadsafe: true

handlers:

#- url: /.*
#  script: main.app

- url: /
  static_files: TaxCalculator.html
  upload: TaxCalculator\.html

#CSS and JS are in folder named "Static". URL says go to that folder, and inside you will find the 

- url: /static
  static_dir: static
