
runtime: python27
api_version: 1
threadsafe: true

handlers:

#- url: /.*
#  script: main.app

- url: /
  static_files: TaxCalculator.html
  upload: TaxCalculator\.html


- url: /page2
  static_files: s.html
  upload: s\.html
