
runtime: python27
api_version: 1
threadsafe: true

handlers:

#- url: /.*
#  script: main.app

- url: /
  static_files: TaxCalculator.html
  upload: TaxCalculator\.html


- url: /.*
  static_files: TaxCalculator.css
  upload: TaxCalculator\.css

- url: /.*
  static_files: TaxCalculator.js
  upload: TaxCalculator\.js
